server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/registro_uni
    username: postgres
    password: 180706
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate.format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: never
    open-in-view: false

app:
  jwt:
    secret: "dGhpcyBpcyBhIHNlY3JldCBrZXkgZm9yIGp3dCB0b2tlbiBnZW5lcmF0aW9uIGluIHRoZSB1bml2ZXJzaWRhZCBuYWNpb25hbCBkZWwgcGFjaWZpY28gYmFja2VuZAo="
    expiration-ms: 86400000
